$LOAD_PATH << File.expand_path('../kyu7', __FILE__)

require 'vowel_count/vowel_count'
require 'exes_and_ohs/exes_and_ohs'
require 'printer_errors/printer_errors'
require 'binary_addition/binary_addition'
require 'binary_addition/binary_addition'
require 'descending_order/descending_order'
require 'mumbling/mumbling'
require 'get_the_middle_character/get_the_middle_character'
require 'jaden_casing_strings/jaden_casing_strings'
require 'disemvowel_trolls/disemvowel_trolls'
require 'complementary_dna/complementary_dna'
require 'you_are_a_square/you_are_a_square'
require 'two_to_one/two_to_one'
require 'sum_of_numbers/sum_of_numbers'
require 'shortest_word/shortest_word'
require 'growth_of_a_population/growth_of_a_population'
require 'credit_card_mask/credit_card_mask'
require 'list_filtering/list_filtering'
require 'categorize_new_member/categorize_new_member'
require 'sum_of_the_first_nth_term_of_series/sum_of_the_first_nth_term_of_series'
require 'sum_of_two_lowest_positive_integers/sum_of_two_lowest_positive_integers'
require 'ones_and_zeros/ones_and_zeros'
require 'dont_give_me_five/dont_give_me_five'
require 'friend_or_foe/friend_or_foe'
require 'count_the_digit/count_the_digit'
